import Images from "../assets/Images";
import KatoFesP2MoveList from "./KatoFesP2MoveList";

export default KatoFesP2Data = {
  hiroyuki:{
    name:"ひ◯ゆき",
    status:{
      HP:500,
      Guts:50,
      ATK:10,
      DEF:10,
    },
    personality:1,
    image:Images.hiroyuki,
    move:{
      move1:KatoFesP2MoveList.ai,
      move2:KatoFesP2MoveList.ronpa,
      move3:KatoFesP2MoveList.zatudan,
    }
  },
  gear:{
    name:"ギア",
    status:{
      HP:1000,
      Guts:100,
      ATK:50,
      DEF:20,
    },
    personality:0.9,
    image:Images.gear,
    move:{
      move1:KatoFesP2MoveList.asupara,
      move2:KatoFesP2MoveList.craver,
      move3:KatoFesP2MoveList.craver,
    }
  },

  nise:{
    name:"糸屯一",
    status:{
      HP:1500,
      Guts:0,
      ATK:60,
      DEF:60,
    },
    personality:0.7,
    image:Images.nise,
    move:{
      move1:KatoFesP2MoveList.watch,
      move2:KatoFesP2MoveList.watch,
      move3:KatoFesP2MoveList.watch,
    }
  },
  naranton:{
    name:"ナラントン◯ラグ",
    status:{
      HP:5000,
      Guts:150,
      ATK:100,
      DEF:100,
    },
    personality:1.4,
    image:Images.naranton,
    move:{
      move1:KatoFesP2MoveList.mai,
      move2:KatoFesP2MoveList.poisson,
      move3:KatoFesP2MoveList.kick,
    }
  },
  golden_naoko:{
    name:"金な◯こ",
    status:{
      HP:10000,
      Guts:300,
      ATK:500,
      DEF:500,
    },
    personality:1.0,
    image:Images.naoko_gold,
    move:{
      move1:KatoFesP2MoveList.mai,
      move2:KatoFesP2MoveList.craver,
      move3:KatoFesP2MoveList.isogashi,
    }
  },
}