import Images from "../assets/Images";
import KatomonMoveList from "./KatomonMoveList";

export default KatomonList = {
  kingdom:{
    name:"加藤純一",
    param:1.5,
    image:Images.katoKingdom,
    description:"985年8月17日に生を受ける。配信界を牛耳るインターネット893。",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  kyomu:{
    name:"加藤純一",
    param:0.5,
    image:Images.katoKyomu,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  suwari:{
    name:"加藤純一",
    param:0.7,
    image:Images.katoUNKsuwari,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  okurei:{
    name:"加藤純一",
    param:2.0,
    image:Images.katoOkurei,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  smile:{
    name:"加藤純一",
    param:1.3,
    image:Images.katoSmile,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  piza:{
    name:"加藤純一",
    param:1.8,
    image:Images.katoSmile,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  hae:{
    name:"加藤純一",
    param:0.4,
    image:Images.katoHae,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  dark:{
    name:"加藤純一",
    param:1.4,
    image:Images.katoDark,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  unk:{
    name:"うんこちゃん",
    param:1.0,
    image:Images.unk,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  naoko_normal:{
    name:"な◯こ",
    param:1.8,
    image:Images.naoko_normal,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  naoko_gold:{
    name:"金な◯こ",
    param:3.5,
    image:Images.naoko_gold,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  hana1:{
    name:"ハナチャン",
    param:4.0,
    image:Images.hana1,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
  hana2:{
    name:"ハナチャン",
    param:5.0,
    image:Images.hana2,
    description:"",
    move:{
      move1:KatomonMoveList.rightStraight,
      move2:KatomonMoveList.gaia,
      move3:KatomonMoveList.escape,
    }
  },
}