import Sounds from "../assets/Sounds";

export default KatoFesP2MoveList = {
    ai:{
      name:"愛してる",
      sound:Sounds.hiroyuki1,//音声ファイルのディレクトリ指定
      power:70,
      consumption_Guts:50,
      add_Guts:0,
      range:500,
      additional1:{
        param:"position1x",//変化するパラメータ(position/HP/ATK,,,)
        change:-50,//変化量
      },
      additional2:{
        param:"p2ATK",//変化するパラメータ(position/HP/ATK,,,)
        change:20,//変化量
      },
      personality:0.7,//移動に影響する性格の設定
    },
    ronpa:{
      name:"論破",
      sound:Sounds.hiroyuki2,//音声ファイルのディレクトリ指定
      power:80,
      consumption_Guts:50,
      add_Guts:0,
      range:400,
      additional1:{
        param:"position1x",//変化するパラメータ(position/HP/ATK,,,)
        change:-50,//変化量
      },
      additional2:{
        param:"p2DEF",//変化するパラメータ(position/HP/ATK,,,)
        change:20,//変化量
      },
      personality:1.3,//移動に影響する性格の設定
    },
    zatudan:{
      name:"雑談",
      sound:Sounds.hiroyuki3,//音声ファイルのディレクトリ指定
      power:20,
      consumption_Guts:70,
      add_Guts:0,
      range:300,
      additional1:{
        param:"position1x",//変化するパラメータ(position/HP/ATK,,,)
        change:-30,//変化量
      },
      personality:1.3,//移動に影響する性格の設定
    },
    asupara:{
      name:"アスパラ",
      sound:Sounds.gear2,//音声ファイルのディレクトリ指定
      power:35,
      consumption_Guts:100,
      add_Guts:50,
      range:200,
      additional1:{
        param:"position1x",//変化するパラメータ(position/HP/ATK,,,)
        change:-80,//変化量
      },
      additional2:{
        param:"p2HP",//変化するパラメータ(position/HP/ATK,,,)
        change:100,//変化量
      },
      additional3:{
        param:"p2DEF",//変化するパラメータ(position/HP/ATK,,,)
        change:100,//変化量
      },
      personality:1.1,//移動に影響する性格の設定
    },
    craver:{
      name:"クレーバー",
      sound:Sounds.gear1,//音声ファイルのディレクトリ指定
      power:150,
      consumption_Guts:110,
      add_Guts:0,
      range:600,
      additional1:{
        param:"position1x",//変化するパラメータ(position/HP/ATK,,,)
        change:-70,//変化量
      },
      additional2:{
        param:"p2DEF",//変化するパラメータ(position/HP/ATK,,,)
        change:50,//変化量
      },
      additional3:{
        param:"p2ATK",//変化するパラメータ(position/HP/ATK,,,)
        change:50,//変化量
      },
      personality:0.7,//移動に影響する性格の設定
    },

    watch:{
      name:"放送を見る",
      sound:Sounds.yatteru,//音声ファイルのディレクトリ指定
      power:70,
      consumption_Guts:70,
      add_Guts:0,
      range:1000,
      additional1:{
        param:"p2DEF",//変化するパラメータ(position/HP/ATK,,,)
        change:50,//変化量
      },
      additional2:{
        param:"p2ATK",//変化するパラメータ(position/HP/ATK,,,)
        change:50,//変化量
      },
      additional3:{
        param:"p2Poisson",//変化するパラメータ(position/HP/ATK,,,)
        change:2,//変化量
      },
      personality:0.6,//移動に影響する性格の設定
    },

    poisson:{
      name:"どくどく",
      sound:Sounds.sepia,//音声ファイルのディレクトリ指定
      power:20,
      consumption_Guts:90,
      add_Guts:10,
      range:500,
      additional1:{
        param:"position1x",//変化するパラメータ(position/HP/ATK,,,)
        change:-10,//変化量
      },
      additional2:{
        param:"p1Poisson",//変化するパラメータ(position/HP/ATK,,,)
        change:2,//変化量
      },
      personality:0.9,//移動に影響する性格の設定
    },
    mai:{
      name:"龍のような舞",
      sound:Sounds.katou2,//音声ファイルのディレクトリ指定
      power:20,
      consumption_Guts:90,
      add_Guts:50,
      range:500,
      additional1:{
        param:"p2Poisson",//変化するパラメータ(position/HP/ATK,,,)
        change:5,//変化量
      },
      additional2:{
        param:"p2ATK",//変化するパラメータ(position/HP/ATK,,,)
        change:100,//変化量
      },
      additional3:{
        param:"p2DEF",//変化するパラメータ(position/HP/ATK,,,)
        change:100,//変化量
      },
      personality:1.5,//移動に影響する性格の設定
    },
    kick:{
      name:"キック",
      sound:Sounds.katou4,//音声ファイルのディレクトリ指定
      power:100,
      consumption_Guts:100,
      add_Guts:50,
      range:200,
      additional1:{
        param:"position1x",//変化するパラメータ(position/HP/ATK,,,)
        change:-150,//変化量
      },
      additional2:{
        param:"p2ATK",//変化するパラメータ(position/HP/ATK,,,)
        change:100,//変化量
      },
      personality:1.1,//移動に影響する性格の設定
    },
    isogashi:{
      name:"いそがしい",
      sound:Sounds.katou3,//音声ファイルのディレクトリ指定
      power:30,
      consumption_Guts:90,
      add_Guts:30,
      range:400,
      additional1:{
        param:"p2HP",//変化するパラメータ(position/HP/ATK,,,)
        change:100,//変化量
      },
      additional2:{
        param:"p2ATK",//変化するパラメータ(position/HP/ATK,,,)
        change:100,//変化量
      },
      additional3:{
        param:"p2DEF",//変化するパラメータ(position/HP/ATK,,,)
        change:100,//変化量
      },
      personality:1.1,//移動に影響する性格の設定
    },
}